# -*- coding: utf-8 -*-
"""Proyecto final programación.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KpB3n6QG-rWdKz1wRLcsxvCrRhPwFi75
"""

### librerias
from datetime import datetime

def inicio():
  import sys
  c = 0
  usuario = str(input("Ingrese el nombre de usuario: "))
  contra = input("Ingrese la contraseña: ")
  if usuario == "consultorio" and contra == "123456":
    print("""
    Bienvenido. Seleccione una opción.
    """)
  else:
    while usuario != "consultorio" or contra != "123456":
      print("""Usuario/contraseña incorrecto. Intente otra vez.
      """)
      usuario = str(input("Ingrese el nombre de usuario: "))
      contra = input("Ingrese la contraseña: ")
      if usuario == "consultorio" and contra == "123456":
        print("""
    Bienvenido. Seleccione una opción.
    """)
        break
      else:
        c = c + 1
      if c == 3:
        sys.exit("Acceso denegado. Se cerrará el programa.")
########
def calc_monto():
  print("""
    –––––––––– Menú de precios ––––––––––
    1. Estudio ($1000)
    2. Colocación de brackets ($5000)
    3. Ajuste de brackets ($3000) 
    4. Paladar ($1500)
    5. Ajuste de paladar ($1500) 
    6. Cambio de Ligas ($500)
    ––––––––––––––––––––––––––––––––––––––
  """)
  procingre = int(input("Ingrese la cantidad de procedimientos a realizar: "))
  conta = 0
  for c in range(0,procingre):
    numprocingre = int(input(f'Ingrese el número del procedimiento {c+1}: '))
    if numprocingre == 1:
      conta = conta + 1000
    elif numprocingre == 2:
      conta = conta + 5000
    elif numprocingre == 3:
      conta = conta + 3000
    elif numprocingre == 4:
      conta = conta + 1500
    elif numprocingre == 5:
      conta = conta + 1500
    elif numprocingre == 6:
      conta = conta + 500
    else:
      print("Elija un procedimiento existente.")
  print(f'El monto total es de ${conta}')
###
def procedimientoslista():
  print("""Procedimientos:
    1. Estudio 
    2. Colocación de brackets 
    3. Ajuste de brackets 
    4. Paladar 
    5. Ajuste de paladar  
    6. Cambio de Ligas 
    """)
  proccitop = int(input("Ingrese el número del procedimiento que se realizará: "))
  while proccitop < 1 or proccitop > 6:
    print ("Elija una opción valida de las anteriores")
    proccitop = str(input("Ingrese el número del procedimiento que se realizará: "))
  proccit = " "

  if proccitop == 1:
    proc.append("Estudio")
  elif proccitop == 2:
    proc.append("Colocación de brackets")
  elif proccitop == 3:
    proc.append("Ajuste de brackets")
  elif proccitop == 4:
    proc.append("Paladar")
  elif proccitop == 5:
    proc.append("Ajuste de paladar")
  elif proccitop == 6:
    proc.append("Cambio de Ligas")
  
  
###
def regispaccitas(paccit):
  if paccit in nombre:
    diacit = str(input("Ingrese el día de la cita (dia mes año): "))
    hicit = str(input("Ingrese la hora de inicio (hr:min:seg): "))
    hfcit = str(input("Ingrese la hora de finalización (hr:min:seg): "))
    
    empalmes (diacit, hicit, hfcit)
    print("Horario Disponible") 
    pacindex = nombre.index(paccit)
    mailcit = email[pacindex]
    dia.append(diacit)
    hi.append(hicit)
    hf.append(hfcit)
    mailci.append(mailcit)
    
  else:
    print("Debe de registrar a un paciente antes de asignarle una cita")

def empalmes(diacit, hicit, hfcit):
  if diacit in dia:
    diaoc = dia.index(diacit)
    format = "%H:%M:%S"
    while datetime.strptime(hicit, format) > datetime.strptime(hi[diaoc], format) and datetime.strptime(hicit, format) < datetime.strptime(hf[diaoc], format) or datetime.strptime(hicit, format) == datetime.strptime(hi[diaoc], format):
      print("Hora ocupada, elija otro horario")
      diacit = str(input("Ingrese el día de la cita (dia mes año): "))
      hicit = str(input("Ingrese la hora de inicio (hr:min:seg): "))
      hfcit = str(input("Ingrese la hora de finalización (hr:min:seg): "))
      empalmes (diacit, hicit, hfcit)
    
    while datetime.strptime(hfcit, format) > datetime.strptime(hi[diaoc], format) and datetime.strptime(hfcit, format) < datetime.strptime(hf[diaoc], format) or datetime.strptime(hfcit, format) == datetime.strptime(hf[diaoc], format):
      print("Hora ocupada, elija otro horario")
      diacit = str(input("Ingrese el día de la cita (dia mes año): "))
      hicit = str(input("Ingrese la hora de inicio (hr:min:seg): "))
      hfcit = str(input("Ingrese la hora de finalización (hr:min:seg): "))
      empalmes (diacit, hicit, hfcit)
  
  

#principales datos de pacientes
nombre = ["Emma Garza","Sofia Canales","Carlos Cardenas"]
email = ["emma@gmail.com", "sofcanal@gmail.com", "ccardenas@gmail.com"]

# programa principal

inicio()
salida = 0
while salida != 6:
  print("""
    –––––––––– Menú de opciones ––––––––––
    1. Registrar paciente
    2. Registrar cita
    3. Ver citas 
    4. Expediente de pacientes registrados
    5. Calcular monto total a pagar 
    6. Cerrar sesión
    ––––––––––––––––––––––––––––––––––––––
    """)
  opc = int(input("Ingrese el número de su opción: "))
  while opc < 1 or opc > 6:
    print("Esa opción no es válida. Seleccione otra.")
    opc = int(input("Ingrese el número de su opción: "))
  if opc == 1:
    #lista de pacientes registrados
    
    edad = [21, 29, 45]
    sexo = ["Femenino", "Femenino", "Masculino"]
    tel = [8174827548, 8137492679, 8136492046]
    alergias = ["NA", "Hipoalergénicos", "Tylenol"]
    ppasados = ["Brackets", "Cirugia Maxilofacial", "Paladar expansor"]
    referido = ["Redes Sociales", "Carlos Cárdenas", "Redes Sociales"]
    notas = ["NA", "consultas frecuentes", "revisiones continuas"]

    # ingresar paciente nuevo
    nombrein = str(input("Ingrese el nombre completo del paciente: "))
    edadin = int(input("Ingrese la edad del paciente: "))
    sexoin = int(input("""Seleccione el sexo del paciente: 
    1. Femenino
    2. Masculino
    """))
    while sexoin < 1 or sexoin > 2:
      print("Esa opción no existe. ")
      sexoin = int(input("""Seleccione el sexo del paciente: 
    1. Femenino
    2. Masculino"""))
    if sexoin == 1:
      sexodef = "Femenino"
    elif sexoin == 2:
      sexodef = "Masculino"
    telin = input("Ingrese el teléfono del paciente: ")
    telindig = len(telin)
    while telindig != 10:
      print("El número telefónico del paciente debe de tener 10 dígitos")
      print("Vuelva a escribirlo")
      telin = input("Ingrese el teléfono del paciente: ")
      telindig = len(telin)
    emailin = str(input("Ingrese el email del paciente: "))
    emailinar = emailin.find("@")
    emailinpun = emailin.find(".com")
    while emailinar == -1 or emailinpun == -1:
      print("El correo electrónico debe de ser una cuenta valida")
      print("Debe de contener una @ y un .com")
      emailin = str(input("Ingrese el email del paciente: "))
      emailinar = emailin.find("@")
      emailinpun = emailin.fin(".com")
    alergiasin = str(input("Ingrese las alergias del paciente: "))
    ppasadosin = str(input("Ingrese procedimientos pasados: "))
    referidoin = str(input("¿Cómo se enteró del consultorio? "))
    notasin = str(input("Notas adicionales: "))
    nombre.append(nombrein)
    edad.append(edadin)
    sexo.append(sexodef)
    tel.append(telin)
    email.append(emailin)
    alergias.append(alergiasin)
    ppasados.append(ppasadosin)
    referido.append(referidoin)
    notas.append(notasin)
    print("Paciente Registrado")

  elif opc == 2:
    dia = ["26 noviembre 2021", "28 noviembre 2021", "30 noviembre 2021"]
    hi = ["11:00:00","13:00:00","14:30:00"]
    hf = ["12:30:00","13:30:00","15:30:00"]
    pac = ["Sofia Canales", "Carlos Cardenas", "Emma Garza"]
    mailci = ["sofcanal@gmail.com", "ccardenas@gmail.com", "emma@gmail.com"]
    proc = ["Estudio", "Cambio de ligas", "Paladar"]

    #registrar cita

    paccit = str(input("Ingrese el nombre del paciente: "))
    regispaccitas(paccit)
    if paccit in nombre:
      procedimientoslista()
      pac.append(paccit)
      print("Cita Agendada")
    
  
  elif opc == 3:
    contacit = 0

    total_citas = len(dia)
    while contacit < (total_citas):
      print(f'Cita #{(contacit+1)}:')
      print(f'''
      Día: {dia[contacit]}
      Hora de inicio:{hi[contacit]}
      Hora de finalización:{hf[contacit]}
      Nombre del paciente: {pac[contacit]}
      Mail del paciente: {mailci[contacit]}
      Procedimiento a realizar: {proc[contacit]}
      ''')
      contacit = contacit + 1
    
  elif opc == 4:
    busqnom = str(input("Ingrese el nombre completo del paciente: "))
    if busqnom in nombre:
      indexnom = nombre.index(busqnom)
      print(f'''
      Nombre: {nombre[indexnom]}
      Edad: {edad[indexnom]}
      Sexo: {sexo[indexnom]}
      Número de teléfono: {tel[indexnom]}
      Email: {email[indexnom]}
      Alergias: {alergias[indexnom]}
      Procedimientos pasados: {ppasados[indexnom]}
      Referido: {referido[indexnom]}
      Notas: {notas[indexnom]}
      ''')
    else:
      print("Paciente no encontrado")

  elif opc == 5:
    calc_monto()
  elif opc == 6:
    print("Cerrando sesión...")
    salida = 6

